#!/bin/sh

set -e

. $(dirname $(readlink -f "$0"))/../inc/envvars
. $(dirname $(readlink -f "$0"))/../inc/localvars

apt-get install ${THIS_APT_INSTALL_OPTIONS} plymouth console-setup debconf-utils less
apt-get install ${THIS_APT_INSTALL_OPTIONS} --install-recommends linux-image-4.9-`dpkg --print-architecture`

exit 0
