#!/bin/sh
#
# https://www.debian.org/releases/stretch/amd64/release-notes/ch-information.en.html#reduced-lsb-support

set -e

. $(dirname $(readlink -f "$0"))/../inc/localvars

PACKAGES="
apt-show-versions
debconf-utils
less
libpam-systemd
lsb-release
"

apt-get install ${THIS_APT_INSTALL_OPTIONS} ${PACKAGES}

exit 0
