#!/bin/sh

set -e

. $(dirname $(readlink -f "$0"))/../inc/localvars

# https://www.debian.org/releases/stretch/amd64/release-notes/ch-information.en.html#reduced-lsb-support
apt-get install ${THIS_APT_INSTALL_OPTIONS} debconf-utils less libpam-systemd lsb-release
# https://www.debian.org/releases/stable/amd64/release-notes/ch-whats-new.en.html#merged-usr

CONFLICTS="
openmediavault-nut
"

CONFLICTS_removed=""

for p in ${CONFLICTS}
do
	dpkg -l | awk '/^ii/ { print $2 }' | grep ${p} && apt-get remove --yes ${p}
	CONFLICTS_removed="${p} ${CONFLICTS_removed}"
done

apt-get install ${THIS_APT_INSTALL_OPTIONS} usrmerge

if [ -n "${CONFLICTS_removed}" ]
then
#	apt-get install ${THIS_APT_INSTALL_OPTIONS} ${CONFLICTS_removed}
	echo "Removed '${CONFLICTS_removed}' because of file conflicts affecting the 'usrmerge' transition."
fi

exit 0
