#!/bin/sh

set -e

# https://github.com/dleidert/openmediavault-upgrade/issues/18
# https://github.com/dleidert/openmediavault-upgrade/issues/31
SERVICES_ENABLE="
docker
systemd-resolved
"

# Services to be re-enabled are not necessary to be re-started. Docker
# for example might need write access to the shares we rounted.
SERVICES_RESTART="
nginx
php7.3-fpm
ssh
systemd-resolved
"

ssh-keygen -A
mv -v /etc/resolv.conf /etc/resolv.conf.bak
ln -svf /var/run/systemd/resolve/resolv.conf /etc/resolv.conf

# Services to be (re-)enabled are not necessary to be (re-)started. Docker for
# example might need write access to the shares we remounted. So don't restart
# the services mentioned in ${SERVICES_ENABLE} by default.
for s in ${SERVICES_ENABLE}
do
        test -n "$(systemctl list-units --all | grep ${s})" && systemctl enable ${s}
done

for s in ${SERVICE_RESTART}
do
	systemctl restart ${s}
done

exit 0
