#!/bin/sh

set -e

. $(dirname $(readlink -f "$0"))/../inc/localvars

currkern="linux-image-`uname -r`+"

apt-get install ${THIS_APT_UPGRADE_OPTIONS} apt-show-versions deborphan

apt-show-versions | grep 'No available version' | awk -F: '{print $1}' | grep -xv -e ${currkern} | xargs apt-get autoremove --purge --yes
# deborphan
while [ -n "$(deborphan)" ]
do
        deborphan | xargs apt-get autoremove --purge --yes ${currkern}
done
dpkg -l | awk '/^rc/ { print $2 }' | xargs apt-get autoremove --purge --yes

exit 0
