#!/bin/sh

set -e

. $(dirname $(readlink -f "$0"))/../inc/localvars

currkern="linux-image-`uname -r`"

apt-get install ${THIS_APT_UPGRADE_OPTIONS} deborphan

while [ -n "$(deborphan | grep -xv -e ${currkern})" ]
do
        deborphan | grep -xv -e ${currkern} | xargs apt-get autoremove --purge --yes
done

exit 0
