#!/bin/sh

set -e

. $(dirname $(readlink -f "$0"))/../inc/omvvars

cat << EOF
******************************************************************************
Successfully upgraded to ${OMV_UPGRADE_RELEASEVERSION} (${OMV_UPGRADE_RELEASENAME}) ..."

Make sure to clear your browser cache before reloading the web GUI!!

Otherwise you might see this error:

        missing 'required' attribute 'enabled'


Please restart your system now.
******************************************************************************
EOF

exit 0
