#!/bin/sh

set -e

. $(dirname $(readlink -f "$0"))/../inc/omvvars

cat << EOF
******************************************************************************
Upgrading system to ${OMV_UPGRADE_RELEASEVERSION} (${OMV_UPGRADE_RELEASENAME}) ...
******************************************************************************
EOF

exit 0
