#!/bin/sh

set -e

. $(dirname $(readlink -f "$0"))/../inc/localvars
. $(dirname $(readlink -f "$0"))/../inc/omvvars

mkdir -p ${THIS_UPGRADE_BACKUP_DIR}

cp -ar --parents /etc /var/lib/dpkg /var/lib/apt/extended_states ${OMV_CACHE_DIR} ${THIS_UPGRADE_BACKUP_DIR}
dpkg --get-selections > ${THIS_UPGRADE_BACKUP_DIR}/package.list

exit 0
