#!/bin/sh
#
# Copyright 2020 Daniel Leidert <daniel.leidert@wgdd.de>

set -e

. $(dirname $(readlink -f "$0"))/../inc/localvars

mkdir -p ${THIS_BACKUP_DIR}

cp -ar --parents /etc /var/lib/dpkg /var/lib/apt/extended_states /var/cache/openmediavault/ ${THIS_BACKUP_DIR}

exit 0
