#!/bin/sh

set  -e

echo "***** Begin /* Local Package List */ *****"
dpkg-query -W -f='${binary:Package}\t${Version}\n' | sort
echo "***** End /* Local Package List */ *****"

echo "***** Begin /* Unit List */ *****"
systemctl list-units --full --no-pager
echo "***** End /* Unit List */ *****"

exit 0
