#!/bin/sh

set  -e

echo "***** Begin /* System Environment */ *****"
# don't print everything
ENVIRONMENT="
COLORTERM
LANG
SHELL
TERM
"
for v in ${ENVIRONMENT}
do
	echo "${v}=$(printenv $v)"
done
echo "***** End /* System Environment */ *****"

echo "***** Begin /* Kernel Version */ *****"
uname -r
echo "***** End /* Kernel Version */ *****"

echo "***** Begin /* Local Package List */ *****"
dpkg-query -W -f='${binary:Package}\t${Version}\n' | sort
echo "***** End /* Local Package List */ *****"

if [ -f "$(which systemctl)" ]
then
	echo "***** Begin /* Unit List */ *****"
	systemctl list-units --full --no-pager
	echo "***** End /* Unit List */ *****"
fi

exit 0
