#!/bin/sh

set -e

SERVICES_STOP="
"

# https://github.com/dleidert/openmediavault-upgrade/issues/18
# There is a likelyhood that this services must be stopped too.
SERVICES_DISABLE="
docker
"

# There is a likelyhood that services to be disabled must be stopped too.
for s in ${SERVICES_DISABLE} ${SERVICES_STOP}
do
	systemctl is-active --quiet ${s}
	test $? -eq 0 && systemctl stop ${s}
done

for s in ${SERVICES_DISABLE}
do
	systemctl is-enabled --quiet ${s}
	test $? -eq 0 && systemctl disable ${s}
done

exit 0
