#!/bin/sh
#
# Copyright 2020 Daniel Leidert <daniel.leidert@wgdd.de>
#
# https://www.debian.org/releases/jessie/amd64/release-notes/ch-information.en.html#systemd-auto-mounts-incompat

set -e

. $(dirname $(readlink -f "$0"))/../inc/localvars

echo "Looking for auto-mount targets lacking the nofail option... "

cp -a ${THIS_FSTAB} ${THIS_FSTAB}.new
awk '($4 ~ /auto/) && ($4 !~ /noauto/) && ($4 !~ /nofail/) {$4 = $4",nofail"} {print}' ${THIS_FSTAB}.new > ${THIS_FSTAB}.fix
mv ${THIS_FSTAB}.fix ${THIS_FSTAB}.new

if [ -n "$(diff -q ${THIS_FSTAB}.new ${THIS_FSTAB} 2>&1)" ]
then
        echo "Writing the proposed changes to ${THIS_FSTAB}"
        echo "$(diff -puN ${THIS_FSTAB} ${THIS_FSTAB}.new)"
        mv ${THIS_FSTAB} ${THIS_FSTAB}.bak
        mv ${THIS_FSTAB}.new ${THIS_FSTAB}
else
        rm -f ${THIS_FSTAB}.new
fi

exit 0
