#!/bin/sh

PLUGINS="
clamav
forkeddaapd
iscsitarget
ldap
lvm2
netatalk
nut
owncloud
route
shairport
usbbackup
"

set -e

for p in ${PLUGINS}
do
	dpkg -l | awk '/^ii/ { print $2 }' | grep openmediavault-${p} && apt-get autoremove --purge --yes openmediavault-${p}
done

set +e
remain="$(dpkg -l | grep ^ii | awk '{print $2}' | grep openmediavault | grep -ve "^\(openmediavault\|openmediavault-keyring\)$")"
set -e

if [ -n "${remain}" ]
then
	apt-get autoremove --yes ${remain}
fi

exit 0
