#!/bin/sh

PLUGINS="
openmediavault-clamav
openmediavault-forkeddaapd
openmediavault-iscsitarget
openmediavault-ldap
openmediavault-lvm2
openmediavault-netatalk
openmediavault-nut
openmediavault-owncloud
openmediavault-route
openmediavault-shairport
openmediavault-tftp
openmediavault-usbbackup
"

set -e

apt-get autoremove --purge --yes ${PLUGINS}

remain="$(dpkg -l | grep ^ii | awk '{print $2}' | grep openmediavault | grep -ve "^\(openmediavault\|openmediavault-keyring\)$")"

apt-get autoremove --purge --yes ${remain}

exit 0
