#!/bin/sh

set -e

. $(dirname $(readlink -f "$0"))/../inc/omvvars

# Cleanup local package archive.
rm -fv ${OMV_DPKGARCHIVE_DIR}/*.deb
cd ${OMV_DPKGARCHIVE_DIR} && apt-ftparchive packages . > Packages

exit 0
