#!/bin/sh
#

set -e

. $(dirname $(readlink -f "$0"))/../inc/localvars

# Keep the old sources list in /etc/apt/sources.list/. That shouldn't be a problem
# because we set the default release.
mv -v ${THIS_APT_SOURCES_LIST} ${THIS_APT_SOURCES_LIST_D}/${THIS_DEBIAN_CODENAME}.list.disabled

# Create the new sources.list.
cat <<EOF > ${THIS_APT_SOURCES_LIST}
deb https://deb.debian.org/debian ${THIS_DEBIAN_CODENAME_NEW} main contrib non-free
deb-src https://deb.debian.org/debian ${THIS_DEBIAN_CODENAME_NEW} main contrib non-free

deb https://deb.debian.org/debian-security ${THIS_DEBIAN_CODENAME_NEW}/updates main contrib non-free
deb-src https://deb.debian.org/debian-security ${THIS_DEBIAN_CODENAME_NEW}/updates main contrib non-free

deb https://deb.debian.org/debian ${THIS_DEBIAN_CODENAME_NEW}-updates main contrib non-free
deb-src https://deb.debian.org/debian ${THIS_DEBIAN_CODENAME_NEW}-updates main contrib non-free
EOF

exit 0
