#!/bin/sh

set -e

. $(dirname $(readlink -f "$0"))/../inc/omvvars

# Upgrade OpenMediaVault source list file.
relname=$(echo ${OMV_UPGRADE_RELEASENAME} | tr "[:upper:]" "[:lower:]" | tr -d "[:space:]")

cat <<EOF > ${OMV_UPGRADE_APTSOURCESLIST}
deb http://packages.openmediavault.org/public ${relname} main
# deb http://downloads.sourceforge.net/project/openmediavault/packages ${relname} main

## Uncomment the following line to add software from the proposed repository.
# deb http://packages.openmediavault.org/public ${relname}-proposed main
# deb http://downloads.sourceforge.net/project/openmediavault/packages ${relname}-proposed main

## This software is not part of OpenMediaVault, but is offered by third-party
## developers as a service to OpenMediaVault users.
# deb http://packages.openmediavault.org/public ${relname} partner
# deb http://downloads.sourceforge.net/project/openmediavault/packages ${relname} partner
EOF

exit 0
