#!/bin/sh

set -e

. $(dirname $(readlink -f "$0"))/../inc/localvars

for list in ${THIS_APT_SOURCES_LIST_D}/omvextras.list ${THIS_APT_SOURCES_LIST_D}/omv-extras-org.list
do
	test -f "${list}" && sed -i "/docker/d" ${list}
done

exit 0
