#!/bin/sh

set -e

. $(dirname $(readlink -f "$0"))/../inc/omvvars

# Create a configuration backup.
if [ ! -e "${OMV_CONFIG_BACKUP_FILE}" ]; then
	cp -v ${OMV_CONFIG_FILE} ${OMV_CONFIG_BACKUP_FILE}
fi

exit 0
