#!/bin/sh

set  -e

test -f "$(which dpkg-query)" || exit 0

echo "***** /* Begin Local Package List */ *****"
dpkg-query -W -f='${binary:Package}\t${Version}\n' | sort
echo "***** /* End Local Package List */ *****"

exit 0
