#!/bin/sh

set -e

# keep nobody's shell
# https://www.debian.org/releases/jessie/amd64/release-notes/ch-information.en.html#base-passwd-hardening
USERS="
backup
nobody
"

for u in ${USERS}
do
	shell="$(awk -F':' -v user="${u}" '$1 == user {print $7}' /etc/passwd | tr '/' '_')"
	test -n "${shell}" && (echo "base-passwd base-passwd/system/user/${u}/shell/${shell}/_usr_sbin_nologin boolean false" | debconf-set-selections)
done

# if PermitRootLogin is not set or not disabled keep it
# https://www.debian.org/releases/jessie/amd64/release-notes/ch-information.en.html#openssh
permit=$(grep -e ^PermitRootLogin /etc/ssh/sshd_config | awk '{print $2}')
if [ -z "${permit}" -o "x${permit}" != "xno" ]
then
	echo "openssh-server openssh-server/permit-root-login boolean false" | debconf-set-selections
fi

# don't restart services without asking
# echo 'libc6 libraries/restart-without-asking boolean false' | debconf-set-selections

exit 0
