#!/bin/sh

set -e

# https://github.com/dleidert/openmediavault-upgrade/issues/3
# If either SECCOMP or SECCOMP_FILTER are disabled, or if SECCOMP is not
# explicitely enabled we go with disabling seccomp support for chronyd.
if [ -n "$(grep 'CONFIG_SECCOMP=n' /boot/config-`uname -r`)" ] ||
   [ -n "$(grep 'CONFIG_SECCOMP_FILTER=n' /boot/config-`uname -r`)" ] ||
   [ -z "$(grep 'CONFIG_SECCOMP=y' /boot/config-`uname -r`)" ]
then
cat << EOF > /etc/default/chrony
# This is a configuration file for /etc/init.d/chrony and
# /lib/systemd/system/chrony.service; it allows you to pass various options to
# the chrony daemon without editing the init script or service file.

# Options to pass to chrony.
# This has been altered by the omv-release-upgrade-5 script (see README.md):
DAEMON_OPTS="-F 0"
EOF
fi

exit 0
