#!/bin/sh

set -e

. $(dirname $(readlink -f "$0"))/../inc/localvars

PACKAGES="
collectd collectd-core rrdtool
"

echo "${PACKAGES}" | while read line
do
	apt-get install ${line} ${THIS_APT_UPGRADE_OPTIONS} --only-upgrade || apt-get install -f
done

exit 0
