#!/bin/sh

set -e

. $(dirname $(readlink -f "$0"))/../inc/localvars
. $(dirname $(readlink -f "$0"))/../inc/omvvars

relname=$(echo ${OMV_UPGRADE_RELEASENAME} | tr "[:upper:]" "[:lower:]" | tr -d "[:space:]")

apt-get dist-upgrade -t ${relname} ${THIS_APT_UPGRADE_OPTIONS} || apt-get install -f

exit 0
