#!/bin/sh

set -e

. $(dirname $(readlink -f "$0"))/../inc/localvars

dpkg -l | awk '/^ii/ { print $2 }' | grep openmediavault-omvextrasorg || exit 0

mkconf_del=
mkconf="/usr/sbin/omv-mkconf"
if [ ! -f "${mkconf}" ]; then
	cat <<EOF > ${mkconf}
#!/bin/sh
exit 0
EOF
	chmod +x ${mkconf}
	mkconf_del="${mkconf}"
fi

#https://forum.openmediavault.org/index.php?thread/27909-omv-5-0-finally-out/&postID=219830#post219830
apt-get remove --purge ${THIS_APT_UPGRADE_OPTIONS} openmediavault-omvextrasorg
wget -qO- https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install | bash

apt-get update ${THIS_APT_UPDATE_OPTIONS}
apt-get dist-upgrade ${THIS_APT_UPGRADE_OPTIONS} || apt-get install -f

test -n "${mkconf_del}" && rm -fv ${mkconf_del}

exit 0
