#!/bin/sh

set -e

kernver="$(uname -r)"

if ($(dpkg --compare-versions "${kernver}" ">=" "4") && $(dpkg --compare-versions "${kernver}" "<<" "4.9")) ||
   ($(dpkg --compare-versions "${kernver}" ">=" "3") && $(dpkg --compare-versions "${kernver}" "<<" "3.16.43"))
then
	echo "Upgrade cannot be done. Please update your kernel first by updating either of these"
	echo
	echo "        linux-image-${THIS_HOST_ARCH} or"
	echo "        linux-image-4.9-${THIS_HOST_ARCH}"
	echo
	echo "to the latest version available in debian-security (no need for backports)."
	echo
        echo "See https://www.debian.org/releases/stretch/amd64/release-notes/ch-information.en.html#pie-is-now-default"
	exit 1
fi

exit 0
